-- Replace the equipment catalog with the club's master tack/equipment list.
-- Existing rows are deactivated (kept so EquipmentStock FKs / history survive),
-- then the new list is upserted as active. Source: prisma/equipment-catalog.ts.
UPDATE "EquipmentCatalog" SET "active" = false;
INSERT INTO "EquipmentCatalog" ("id","category","name","code","unit","defaultThreshold","notes","active","createdAt","updatedAt") VALUES
('tack_saddles','tack','Saddles','tack_saddles','piece',5,'Colour, Jumping Saddle, Trooper saddle, Polo Saddle etc',true,NOW(),NOW()),
('tack_bridles','tack','Bridles','tack_bridles','piece',5,NULL,true,NOW(),NOW()),
('tack_stirrup_belt','tack','Stirrup Belt','tack_stirrup_belt','piece',5,NULL,true,NOW(),NOW()),
('tack_stirrup_steel','tack','Stirrup Steel','tack_stirrup_steel','pair',5,NULL,true,NOW(),NOW()),
('tack_reins','tack','Reins','tack_reins','pair',5,NULL,true,NOW(),NOW()),
('tack_bit','tack','Bit','tack_bit','piece',5,NULL,true,NOW(),NOW()),
('tack_snaffle','tack','Snaffle','tack_snaffle','piece',5,NULL,true,NOW(),NOW()),
('tack_pelham','tack','Pelham','tack_pelham','piece',5,NULL,true,NOW(),NOW()),
('tack_curb_bit','tack','Curb Bit','tack_curb_bit','piece',5,NULL,true,NOW(),NOW()),
('tack_girth','tack','Girth','tack_girth','piece',5,NULL,true,NOW(),NOW()),
('tack_halter','tack','Halter','tack_halter','piece',5,NULL,true,NOW(),NOW()),
('tack_saddle_pad','tack','Saddle Pad','tack_saddle_pad','piece',5,NULL,true,NOW(),NOW()),
('tack_gel_pad','tack','Gel Pad','tack_gel_pad','piece',5,NULL,true,NOW(),NOW()),
('tack_fur_pad','tack','Pur Pad / Fur Pads','tack_fur_pad','piece',5,NULL,true,NOW(),NOW()),
('tack_blanket','tack','Blanket','tack_blanket','piece',5,NULL,true,NOW(),NOW()),
('tack_noseband','tack','Noseband','tack_noseband','piece',5,NULL,true,NOW(),NOW()),
('tack_martingale','tack','Martingale','tack_martingale','piece',5,NULL,true,NOW(),NOW()),
('tack_muzzle','tack','Muzzle','tack_muzzle','piece',5,NULL,true,NOW(),NOW()),
('tack_earnet','tack','Earnet','tack_earnet','piece',5,NULL,true,NOW(),NOW()),
('tack_hoof_cover','tack','Hoof Cover','tack_hoof_cover','piece',5,NULL,true,NOW(),NOW()),
('tack_bandage_wraps','tack','Horse Bandage Wraps','tack_bandage_wraps','piece',5,NULL,true,NOW(),NOW()),
('tack_breastplate','tack','Breastplate / Breastcollar','tack_breastplate','piece',5,NULL,true,NOW(),NOW()),
('tack_blinkers','tack','Blinkers','tack_blinkers','piece',5,NULL,true,NOW(),NOW()),
('tack_crupper','tack','Crupper','tack_crupper','piece',5,NULL,true,NOW(),NOW()),
('tack_tendon_boots','tack','Bell / Tendon Boots','tack_tendon_boots','pair',5,NULL,true,NOW(),NOW()),
('tack_lunging_reins','tack','Lunging Reins','tack_lunging_reins','piece',5,NULL,true,NOW(),NOW()),
('tack_side_reins','tack','Side Reins','tack_side_reins','pair',5,NULL,true,NOW(),NOW()),
('tack_over_girth','tack','Over Girth','tack_over_girth','piece',5,NULL,true,NOW(),NOW()),
('tack_winter_blanket','tack','Winter Blanket / Jhool','tack_winter_blanket','piece',5,NULL,true,NOW(),NOW()),
('tack_lance_holder','tack','Lance Holder','tack_lance_holder','piece',5,NULL,true,NOW(),NOW()),
('tack_pony_saddle','tack','Pony Saddles','tack_pony_saddle','piece',5,NULL,true,NOW(),NOW()),
('tack_pony_bridle','tack','Pony Bridles','tack_pony_bridle','piece',5,NULL,true,NOW(),NOW()),
('tack_pony_bit','tack','Pony Bits','tack_pony_bit','piece',5,NULL,true,NOW(),NOW()),
('tack_pony_stirrup','tack','Pony Stirrups','tack_pony_stirrup','pair',5,NULL,true,NOW(),NOW()),
('groom_curry_comb','grooming','Curry Comb','groom_curry_comb','piece',5,NULL,true,NOW(),NOW()),
('groom_dandy_brush','grooming','Dandy Brush','groom_dandy_brush','piece',5,NULL,true,NOW(),NOW()),
('groom_body_brush','grooming','Body Brush','groom_body_brush','piece',5,NULL,true,NOW(),NOW()),
('groom_mane_tail_brush','grooming','Mane & Tail Brush / Comb','groom_mane_tail_brush','piece',5,NULL,true,NOW(),NOW()),
('groom_hoof_pick','grooming','Hoof Pick','groom_hoof_pick','piece',5,NULL,true,NOW(),NOW()),
('groom_rubber_gloves','grooming','Rubber Gloves','groom_rubber_gloves','pair',5,NULL,true,NOW(),NOW()),
('groom_sponges_cloth','grooming','Sponges & Cloth','groom_sponges_cloth','piece',5,NULL,true,NOW(),NOW()),
('groom_massage_pad','grooming','Massage Pad','groom_massage_pad','piece',5,NULL,true,NOW(),NOW()),
('groom_sweat_scraper','grooming','Sweat Scraper','groom_sweat_scraper','piece',5,NULL,true,NOW(),NOW()),
('groom_hoof_brush','grooming','Hoof Brush','groom_hoof_brush','piece',5,NULL,true,NOW(),NOW()),
('groom_hoof_oil','grooming','Hoof Oil','groom_hoof_oil','litre',5,NULL,true,NOW(),NOW()),
('groom_scissors','grooming','Scissors','groom_scissors','piece',5,NULL,true,NOW(),NOW()),
('groom_fly_spray','grooming','Fly Spray','groom_fly_spray','piece',5,NULL,true,NOW(),NOW()),
('groom_coat_polish','grooming','Coat Polish','groom_coat_polish','piece',5,NULL,true,NOW(),NOW()),
('groom_shampoo','grooming','Shampoo / Conditioner','groom_shampoo','litre',5,NULL,true,NOW(),NOW()),
('groom_fleece_machine','grooming','Fleece Removing Machine','groom_fleece_machine','piece',5,NULL,true,NOW(),NOW()),
('stable_hay_net','stable','Hay Net','stable_hay_net','piece',5,NULL,true,NOW(),NOW()),
('stable_mats','stable','Stable Mats','stable_mats','piece',5,NULL,true,NOW(),NOW()),
('stable_fans','stable','Fans','stable_fans','piece',5,NULL,true,NOW(),NOW()),
('stable_coolers','stable','Coolers','stable_coolers','piece',5,NULL,true,NOW(),NOW()),
('stable_buckets','stable','Buckets','stable_buckets','piece',5,NULL,true,NOW(),NOW()),
('stable_fodder_tub','stable','Fodder Mix Tub','stable_fodder_tub','piece',5,NULL,true,NOW(),NOW()),
('stable_forked_spade','stable','Forked Hay Spade (Punji)','stable_forked_spade','piece',5,NULL,true,NOW(),NOW()),
('stable_spade','stable','Spade','stable_spade','piece',5,NULL,true,NOW(),NOW()),
('stable_waste_trolley','stable','Waste Trolley','stable_waste_trolley','piece',5,NULL,true,NOW(),NOW()),
('rider_helmet','rider','Helmet','rider_helmet','piece',5,NULL,true,NOW(),NOW()),
('rider_breeches','rider','Breeches','rider_breeches','piece',5,NULL,true,NOW(),NOW()),
('rider_long_boots','rider','Long Boots','rider_long_boots','pair',5,NULL,true,NOW(),NOW()),
('rider_short_boots','rider','Short Boots','rider_short_boots','pair',5,NULL,true,NOW(),NOW()),
('rider_chest_guard','rider','Chest Guard','rider_chest_guard','piece',5,NULL,true,NOW(),NOW()),
('rider_whip','rider','Whip','rider_whip','piece',5,NULL,true,NOW(),NOW()),
('rider_spurs','rider','Spurs','rider_spurs','pair',5,NULL,true,NOW(),NOW()),
('rider_chaps','rider','Chaps','rider_chaps','pair',5,NULL,true,NOW(),NOW()),
('rider_tshirts','rider','T-Shirts','rider_tshirts','piece',5,NULL,true,NOW(),NOW()),
('rider_caps','rider','Caps','rider_caps','piece',5,NULL,true,NOW(),NOW()),
('rider_track_suits','rider','Track Suits','rider_track_suits','piece',5,NULL,true,NOW(),NOW()),
('rider_gloves','rider','Gloves','rider_gloves','pair',5,NULL,true,NOW(),NOW()),
('rider_knee_guard','rider','Knee Guard','rider_knee_guard','pair',5,NULL,true,NOW(),NOW()),
('sport_polo_mallet','sports','Polo Mallet','sport_polo_mallet','piece',5,'Sizes',true,NOW(),NOW()),
('sport_polo_balls','sports','Polo Balls','sport_polo_balls','piece',5,'Types',true,NOW(),NOW()),
('sport_lance_intl','sports','Lance International','sport_lance_intl','piece',5,'2 Piece',true,NOW(),NOW()),
('sport_lance_indian','sports','Lance Indian','sport_lance_indian','piece',5,NULL,true,NOW(),NOW()),
('sport_ceremonial_lance','sports','Ceremonial Lance','sport_ceremonial_lance','piece',5,NULL,true,NOW(),NOW()),
('sport_sword_intl','sports','Sword International','sport_sword_intl','piece',5,NULL,true,NOW(),NOW()),
('sport_lance_bag','sports','Lance Bag','sport_lance_bag','piece',5,NULL,true,NOW(),NOW()),
('sport_sword_bag','sports','Sword Bag','sport_sword_bag','piece',5,NULL,true,NOW(),NOW()),
('sport_pegs','sports','Pegs','sport_pegs','piece',5,NULL,true,NOW(),NOW()),
('sport_ring_stands','sports','Ring Stands','sport_ring_stands','piece',5,NULL,true,NOW(),NOW()),
('sport_jumping_wings','sports','Jumping Wings','sport_jumping_wings','pair',5,NULL,true,NOW(),NOW()),
('sport_jumping_poles','sports','Jumping Poles','sport_jumping_poles','piece',5,NULL,true,NOW(),NOW()),
('sport_red_flags','sports','Red Flags','sport_red_flags','piece',5,NULL,true,NOW(),NOW()),
('sport_white_flags','sports','White Flags','sport_white_flags','piece',5,NULL,true,NOW(),NOW()),
('sport_pole_blocks','sports','Pole Number Blocks','sport_pole_blocks','piece',5,NULL,true,NOW(),NOW()),
('sport_measuring_wheel','sports','Measuring Wheel','sport_measuring_wheel','piece',5,NULL,true,NOW(),NOW()),
('sport_rings_tp','sports','Rings TP','sport_rings_tp','piece',5,NULL,true,NOW(),NOW()),
('sport_dressage_markers','sports','Dressage Markers','sport_dressage_markers','piece',5,NULL,true,NOW(),NOW()),
('sport_jumping_hooks','sports','Jumping Hooks','sport_jumping_hooks','piece',5,NULL,true,NOW(),NOW()),
('sport_polo_casket','sports','Polo Wooden Casket','sport_polo_casket','piece',5,NULL,true,NOW(),NOW()),
('sport_stop_watch','sports','Stop Watch','sport_stop_watch','piece',5,NULL,true,NOW(),NOW()),
('sport_riding_bibs','sports','Riding Bibs','sport_riding_bibs','piece',5,NULL,true,NOW(),NOW()),
('sport_marking_cones','sports','Marking Cones','sport_marking_cones','piece',5,NULL,true,NOW(),NOW()),
('sport_mls_stand','sports','Mallet / Lance / Sword Stand','sport_mls_stand','piece',5,NULL,true,NOW(),NOW()),
('vet_thermometer','vet','Thermometer','vet_thermometer','piece',5,NULL,true,NOW(),NOW())
ON CONFLICT ("code") DO UPDATE SET
  "category" = EXCLUDED."category",
  "name" = EXCLUDED."name",
  "unit" = EXCLUDED."unit",
  "defaultThreshold" = EXCLUDED."defaultThreshold",
  "notes" = EXCLUDED."notes",
  "active" = true,
  "updatedAt" = NOW();
