import { redirect } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { requireSession } from "@/lib/auth";
import { scopeCentre } from "@/lib/tenancy";
import { getOrgIdForSession } from "@/lib/features-gate";
import { can } from "@/lib/permissions";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { EmptyState } from "@/components/ui/empty-state";
import { CheckCheck } from "lucide-react";
import { formatDate } from "@/lib/utils";
import { ResponsiveTable } from "@/components/ui/responsive-table";
import { ReviewButtons } from "./approvals-client";
import { formatEnum, roleLabel } from "@/lib/labels";
import { CHANGE_REVIEWER_ROLES, isChangeKind, mayReviewChange } from "@/lib/change-requests";

const TYPE_LABEL: Record<string, string> = {
  equipment_stock_change: "Stock change",
  horse_update: "Horse change",
  horse_create: "New horse",
};
export const dynamic = "force-dynamic";

export default async function ApprovalsPage() {
  const session = await requireSession();
  const centreId = scopeCentre(session);
  const canReviewGeneric = can(session.role, "leave.approve");
  // Anyone who can decide SOMETHING here sees the centre's queue; everyone
  // else — a coach — sees only what they asked for. This page used to list
  // every request to anyone who opened it.
  const seesAll = canReviewGeneric || CHANGE_REVIEWER_ROLES.includes(session.role);

  // ApprovalRequest has a scalar centreId but NO `centre` relation, so the
  // tenantWhere() relation-filter can't be used here. Bound by org instead:
  // resolve the org's centres and constrain to them, so an HQ user's "all
  // centres" (centreId=null) can't fall through to an empty filter that leaks
  // every org's approvals. Fail closed if the org can't be resolved.
  const orgId = await getOrgIdForSession(session);
  if (!orgId) redirect("/no-organisation");
  const orgCentres = await prisma.centre.findMany({
    where: { orgId },
    select: { id: true },
  });
  const orgCentreIds = orgCentres.map((c) => c.id);

  const where: any = {
    // scopeCentre() reads the client-controlled ew_hq_centre cookie, so the
    // picked centre must be INTERSECTED with the org's own, never replace it.
    centreId: centreId && orgCentreIds.includes(centreId) ? centreId : { in: orgCentreIds },
    ...(seesAll ? {} : { requestedBy: session.userId }),
  };

  const rows = await prisma.approvalRequest.findMany({
    where,
    orderBy: [{ status: "asc" }, { createdAt: "desc" }],
    take: 200,
  });

  // Resolve requester names in one round-trip.
  const requesterIds = Array.from(new Set(rows.map((r) => r.requestedBy)));
  const requesters = requesterIds.length
    ? await prisma.user.findMany({
        where: { id: { in: requesterIds } },
        select: { id: true, name: true, role: true },
      })
    : [];
  const userById = new Map(requesters.map((u) => [u.id, u]));

  const pending = rows.filter((r) => r.status === "pending");

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold">Approvals</h1>
      </div>

      <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
        <Kpi label="Pending" value={pending.length} tone={pending.length > 0 ? "amber" : undefined} />
        <Kpi label="Approved" value={rows.filter((r) => r.status === "approved").length} />
        <Kpi label="Rejected" value={rows.filter((r) => r.status === "rejected").length} />
        <Kpi label="Total" value={rows.length} />
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Requests</CardTitle>
        </CardHeader>
        <CardContent>
          {rows.length === 0 ? (
            // Approvals are generated by other flows (rider self-enrol,
            // expenses, requisitions) — there's no "create approval"
            // action here. Empty state is informative, not a CTA.
            <EmptyState
              icon={<CheckCheck className="h-8 w-8" />}
              title="Nothing Waiting for Your Review"
              body="When a rider self-enrols, a coach submits a requisition, or a leave request lands, it shows up here."
            />
          ) : (
            <ResponsiveTable
              rows={rows}
              getRowKey={(r) => r.id}
              columns={[
                {
                  key: "request",
                  header: "Request",
                  primary: true,
                  cell: (r) => (
                    <>
                      <div className="font-medium">{r.title}</div>
                      {r.body && <div className="mt-0.5 text-xs text-muted-foreground">{r.body}</div>}
                      {r.reviewNotes && (
                        <div className="mt-1 rounded bg-muted/40 px-2 py-1 text-xs">
                          <span className="text-muted-foreground">Review:</span> {r.reviewNotes}
                        </div>
                      )}
                    </>
                  ),
                },
                {
                  key: "from",
                  header: "From",
                  className: "text-xs",
                  cell: (r) => {
                    const user = userById.get(r.requestedBy);
                    return (
                      <>
                        {user?.name ?? "—"}
                        {user && <div className="text-[10px] text-muted-foreground">{roleLabel(user.role)}</div>}
                      </>
                    );
                  },
                },
                {
                  key: "type",
                  header: "Type",
                  className: "text-xs",
                  cell: (r) => TYPE_LABEL[r.entityType] ?? r.entityType,
                },
                {
                  key: "status",
                  header: "Status",
                  cell: (r) => (
                    <Badge
                      variant={
                        r.status === "approved" ? "success"
                        : r.status === "rejected" ? "destructive"
                        : r.status === "cancelled" ? "outline"
                        : "warning"
                      }
                    >
                      {formatEnum(r.status)}
                    </Badge>
                  ),
                },
                {
                  // Only meaningful for a coach's change: approving it is what
                  // writes it, so say plainly whether it has been written.
                  key: "applied",
                  header: "Applied",
                  className: "text-xs text-muted-foreground",
                  cell: (r) =>
                    !isChangeKind(r.entityType)
                      ? "—"
                      : r.appliedAt
                        ? `✓ ${formatDate(r.appliedAt)}`
                        : r.status === "pending"
                          ? "Waiting"
                          : "Not applied",
                },
                {
                  key: "created",
                  header: "Created",
                  className: "text-xs text-muted-foreground",
                  cell: (r) => formatDate(r.createdAt),
                },
                {
                  key: "actions",
                  header: "",
                  className: "text-right",
                  cell: (r) => {
                    const isMine = r.requestedBy === session.userId;
                    const canReview = isChangeKind(r.entityType)
                      ? mayReviewChange(session.role, r.requestedBy, session.userId)
                      : canReviewGeneric;
                    return r.status === "pending" ? (
                      <ReviewButtons id={r.id} canReview={canReview} isMine={isMine} />
                    ) : null;
                  },
                },
              ]}
            />
          )}
        </CardContent>
      </Card>
    </div>
  );
}

function Kpi({ label, value, tone }: { label: string; value: number; tone?: "amber" }) {
  return (
    <div className="rounded-lg border bg-card p-3">
      <div className="text-[10px] uppercase tracking-wider text-muted-foreground">{label}</div>
      <div className={`mt-1 text-2xl font-semibold ${tone === "amber" ? "text-amber-700 dark:text-amber-400" : ""}`}>
        {value}
      </div>
    </div>
  );
}
