// Public landing for staff hiring invites. The recipient hits this via a
// /r/<code> short link generated by admin/super-admin. They fill name,
// email, phone, then submit; we create a User with status=pending_approval
// and the admin sees them in the pending-approvals queue.

import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { StaffRegisterForm } from "./form";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

export const dynamic = "force-dynamic";

export default async function StaffRegisterPage({ params }: { params: { code: string } }) {
  const code = params.code.toUpperCase();
  if (!/^[0-9A-Z]{4,16}$/.test(code)) notFound();

  const link = await prisma.shortLink.findUnique({
    where: { code },
    include: { centre: { select: { name: true } } },
  });
  if (!link || link.kind !== "staff_hire") notFound();
  if (link.expiresAt && link.expiresAt < new Date()) {
    return (
      <main className="flex min-h-screen items-center justify-center bg-secondary p-4">
        <Card className="w-full max-w-md">
          <CardHeader>
            <CardTitle>Invite expired</CardTitle>
            <CardDescription>
              Ask the admin to send you a fresh invite.
            </CardDescription>
          </CardHeader>
        </Card>
      </main>
    );
  }

  return (
    <main className="flex min-h-screen items-center justify-center bg-secondary p-4">
      <Card className="w-full max-w-md">
        <CardHeader>
          <CardTitle>Join {link.centre.name}</CardTitle>
          <CardDescription>
            Fill in your details below. Once submitted, the centre admin will review and activate
            your account — you'll get an email when it's ready.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <StaffRegisterForm code={code} centreName={link.centre.name} />
        </CardContent>
      </Card>
    </main>
  );
}
