import { NextRequest, NextResponse } from "next/server";
import { Prisma } from "@prisma/client";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { getOwnerSession } from "@/lib/owner-auth";
import {
  generateTotpSecret,
  otpauthUrl,
  verifyTotp,
  generateRecoveryCodes,
  hashRecoveryCode,
} from "@/lib/totp";

// GET — start enrollment. Returns a fresh otpauth URL the user pastes into
// their authenticator app. We DO NOT save the secret yet — confirm by
// verifying a code via PATCH before persisting.
export async function GET() {
  const session = await getOwnerSession();
  if (!session) return NextResponse.json({ error: "UNAUTHENTICATED" }, { status: 401 });
  const owner = await prisma.platformUser.findUnique({
    where: { id: session.ownerId },
    select: { email: true, twoFactor: true },
  });
  if (!owner) return NextResponse.json({ error: "NOT_FOUND" }, { status: 404 });
  if (owner.twoFactor) return NextResponse.json({ error: "ALREADY_ENROLLED" }, { status: 409 });

  const secret = generateTotpSecret();
  const url = otpauthUrl({ secret, label: owner.email, issuer: "Equiwings Owner" });
  return NextResponse.json({ secret, otpauthUrl: url });
}

const enrollSchema = z.object({ secret: z.string().min(16), code: z.string().regex(/^\d{6}$/) });

// PATCH — finalise enrollment: client posts the secret it received from GET
// plus a code freshly generated by the authenticator. Only persists on a
// match, so we don't silently break login with a wrong secret.
export async function PATCH(req: NextRequest) {
  const session = await getOwnerSession();
  if (!session) return NextResponse.json({ error: "UNAUTHENTICATED" }, { status: 401 });
  const body = await req.json().catch(() => null);
  const parsed = enrollSchema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json({ error: "VALIDATION", details: parsed.error.flatten() }, { status: 400 });
  }
  const { secret, code } = parsed.data;
  if (!verifyTotp(secret, code)) {
    return NextResponse.json({ error: "BAD_CODE" }, { status: 400 });
  }
  // Generate single-use recovery codes at enrol time. Plaintext is shown to
  // the user ONCE — only hashes are persisted, so a DB leak can't reveal
  // them later.
  const recoveryPlain = generateRecoveryCodes(8);
  const recoveryHashes = recoveryPlain.map(hashRecoveryCode);
  await prisma.platformUser.update({
    where: { id: session.ownerId },
    data: {
      totpSecret: secret,
      twoFactor: true,
      totpLastStep: null,
      // jsonb column — pass the array directly.
      totpRecoveryCodesJson: recoveryHashes,
    },
  });
  await prisma.platformAuditLog.create({
    data: { actorId: session.ownerId, action: "owner.2fa_enabled" },
  });
  return NextResponse.json({ ok: true, recoveryCodes: recoveryPlain });
}

// DELETE — disable 2FA. Requires a current code to prevent a stolen-cookie
// attacker from turning it off.
const disableSchema = z.object({ code: z.string().regex(/^\d{6}$/) });

export async function DELETE(req: NextRequest) {
  const session = await getOwnerSession();
  if (!session) return NextResponse.json({ error: "UNAUTHENTICATED" }, { status: 401 });
  const body = await req.json().catch(() => null);
  const parsed = disableSchema.safeParse(body);
  if (!parsed.success) return NextResponse.json({ error: "VALIDATION" }, { status: 400 });

  const owner = await prisma.platformUser.findUnique({
    where: { id: session.ownerId },
    select: { totpSecret: true, twoFactor: true },
  });
  if (!owner?.twoFactor || !owner.totpSecret) {
    return NextResponse.json({ error: "NOT_ENROLLED" }, { status: 409 });
  }
  if (!verifyTotp(owner.totpSecret, parsed.data.code)) {
    return NextResponse.json({ error: "BAD_CODE" }, { status: 400 });
  }
  await prisma.platformUser.update({
    where: { id: session.ownerId },
    data: {
      totpSecret: null,
      twoFactor: false,
      totpLastStep: null,
      totpRecoveryCodesJson: Prisma.DbNull,
    },
  });
  await prisma.platformAuditLog.create({
    data: { actorId: session.ownerId, action: "owner.2fa_disabled" },
  });
  return NextResponse.json({ ok: true });
}
