import { NextRequest, NextResponse } from "next/server";
import { Prisma } from "@prisma/client";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { getSession } from "@/lib/auth";
import { audit } from "@/lib/audit";
import {
  generateTotpSecret,
  otpauthUrl,
  verifyTotp,
  generateRecoveryCodes,
  hashRecoveryCode,
} from "@/lib/totp";

// Tenant-side 2FA enrollment. Mirrors the owner-portal flow at
// /api/owner/account/totp — clone, not shared, because the two auth
// domains (tenant vs platform) deliberately stay separate.

// GET — start enrollment. Returns a fresh otpauth URL the user scans.
// Does NOT persist the secret until the user verifies a code via PATCH.
export async function GET() {
  const session = await getSession();
  if (!session) return NextResponse.json({ error: "UNAUTHENTICATED" }, { status: 401 });
  const user = await prisma.user.findUnique({
    where: { id: session.userId },
    select: { email: true, twoFactor: true },
  });
  if (!user) return NextResponse.json({ error: "NOT_FOUND" }, { status: 404 });
  if (user.twoFactor) return NextResponse.json({ error: "ALREADY_ENROLLED" }, { status: 409 });

  const secret = generateTotpSecret();
  const url = otpauthUrl({ secret, label: user.email, issuer: "Equiwings" });
  return NextResponse.json({ secret, otpauthUrl: url });
}

const enrollSchema = z.object({ secret: z.string().min(16), code: z.string().regex(/^\d{6}$/) });

// PATCH — finalise enrollment with a code freshly generated by the
// authenticator. Persists secret + flips twoFactor=true only on match.
export async function PATCH(req: NextRequest) {
  const session = await getSession();
  if (!session) return NextResponse.json({ error: "UNAUTHENTICATED" }, { status: 401 });
  const body = await req.json().catch(() => null);
  const parsed = enrollSchema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json({ error: "VALIDATION", details: parsed.error.flatten() }, { status: 400 });
  }
  const { secret, code } = parsed.data;
  if (!verifyTotp(secret, code)) {
    return NextResponse.json({ error: "BAD_CODE" }, { status: 400 });
  }
  // Mint 8 one-shot recovery codes; show plaintext once, persist hashes only.
  const recoveryPlain = generateRecoveryCodes(8);
  const recoveryHashes = recoveryPlain.map(hashRecoveryCode);
  await prisma.user.update({
    where: { id: session.userId },
    data: {
      totpSecret: secret,
      twoFactor: true,
      totpLastStep: null,
      // jsonb column — pass the array directly (Prisma serialises it).
      totpRecoveryCodesJson: recoveryHashes,
    },
  });
  await audit({ userId: session.userId, action: "auth.2fa_enabled", tableName: "user", rowId: session.userId });
  return NextResponse.json({ ok: true, recoveryCodes: recoveryPlain });
}

const disableSchema = z.object({ code: z.string().regex(/^\d{6}$/) });

// DELETE — disable 2FA. Requires a current code so a stolen-cookie
// attacker can't silently turn off the second factor.
export async function DELETE(req: NextRequest) {
  const session = await getSession();
  if (!session) return NextResponse.json({ error: "UNAUTHENTICATED" }, { status: 401 });
  const body = await req.json().catch(() => null);
  const parsed = disableSchema.safeParse(body);
  if (!parsed.success) return NextResponse.json({ error: "VALIDATION" }, { status: 400 });

  const user = await prisma.user.findUnique({
    where: { id: session.userId },
    select: { totpSecret: true, twoFactor: true },
  });
  if (!user?.twoFactor || !user.totpSecret) {
    return NextResponse.json({ error: "NOT_ENROLLED" }, { status: 409 });
  }
  if (!verifyTotp(user.totpSecret, parsed.data.code)) {
    return NextResponse.json({ error: "BAD_CODE" }, { status: 400 });
  }
  await prisma.user.update({
    where: { id: session.userId },
    data: { totpSecret: null, twoFactor: false, totpLastStep: null, totpRecoveryCodesJson: Prisma.DbNull },
  });
  await audit({ userId: session.userId, action: "auth.2fa_disabled", tableName: "user", rowId: session.userId });
  return NextResponse.json({ ok: true });
}
